// นิยามภูมิภาค — อ่านโดย index.html และ collect.py (สร้างรวมอัตโนมัติ)
window.REGIONS = {
  "chiangmai": {
    "name": "เชียงใหม่",
    "country": "TH",
    "lang": "th",
    "currency": "฿",
    "origin": {
      "name": "ประตูท่าแพ",
      "lat": 18.7877,
      "lng": 98.9931
    },
    "searchRadiusKm": 30,
    "mapZoom": 12,
    "seeds": [
      "ข้าวซอย เชียงใหม่",
      "อาหารเหนือ เชียงใหม่",
      "ขนมจีนน้ำเงี้ยว เชียงใหม่",
      "ก๋วยเตี๋ยว เชียงใหม่",
      "ข้าวมันไก่ เชียงใหม่",
      "ข้าวขาหมู เชียงใหม่",
      "ข้าวแกง เชียงใหม่",
      "อาหารเช้า เชียงใหม่",
      "ส้มตำ ไก่ย่าง เชียงใหม่",
      "อาหารอีสาน เชียงใหม่",
      "ต้มยำ เชียงใหม่",
      "อาหารตามสั่ง เชียงใหม่",
      "ร้านอาหารญี่ปุ่น เชียงใหม่",
      "ซูชิ เชียงใหม่",
      "ราเมง เชียงใหม่",
      "อาหารเกาหลี เชียงใหม่",
      "ปิ้งย่างเกาหลี เชียงใหม่",
      "อาหารจีน เชียงใหม่",
      "ติ่มซำ เชียงใหม่",
      "อาหารเวียดนาม เชียงใหม่",
      "อาหารอินเดีย เชียงใหม่",
      "อิตาเลียน พิซซ่า เชียงใหม่",
      "สเต็ก เชียงใหม่",
      "เบอร์เกอร์ เชียงใหม่",
      "ซีฟู้ด เชียงใหม่",
      "หมูกระทะ เชียงใหม่",
      "สุกี้ ชาบู เชียงใหม่",
      "อาหารมังสวิรัติ เจ เชียงใหม่",
      "ร้านอาหารริมน้ำ เชียงใหม่",
      "คาเฟ่ เชียงใหม่",
      "คาเฟ่วิวดอย เชียงใหม่",
      "คาเฟ่ นิมมาน",
      "ร้านกาแฟ specialty เชียงใหม่",
      "ร้านกาแฟ แม่ริม",
      "ร้านขนมหวาน เชียงใหม่",
      "เบเกอรี่ เชียงใหม่",
      "บาร์ ค็อกเทล เชียงใหม่",
      "ร้านนั่งชิล ดนตรีสด เชียงใหม่",
      "วัด เชียงใหม่",
      "ที่เที่ยว เชียงใหม่",
      "น้ำตก เชียงใหม่",
      "จุดชมวิว เชียงใหม่",
      "ตลาด เชียงใหม่",
      "ถนนคนเดิน เชียงใหม่",
      "พิพิธภัณฑ์ เชียงใหม่",
      "สวนสาธารณะ เชียงใหม่",
      "ที่เที่ยว แม่ริม",
      "ที่เที่ยว หางดง",
      "ที่เที่ยว สันกำแพง"
    ]
  },
  "chiangrai": {
    "name": "เชียงราย",
    "country": "TH",
    "lang": "th",
    "currency": "฿",
    "origin": {
      "name": "หอนาฬิกาเชียงราย",
      "lat": 19.9075,
      "lng": 99.8309
    },
    "searchRadiusKm": 40,
    "mapZoom": 12,
    "seeds": [
      "ร้านอาหาร เชียงราย",
      "คาเฟ่ เชียงราย",
      "วัด เชียงราย",
      "ที่เที่ยว เชียงราย",
      "ตลาด เชียงราย",
      "จุดชมวิว เชียงราย"
    ]
  },
  "bangkok": {
    "name": "กรุงเทพฯ",
    "country": "TH",
    "lang": "th",
    "currency": "฿",
    "origin": {
      "name": "สยาม",
      "lat": 13.7457,
      "lng": 100.5331
    },
    "searchRadiusKm": 25,
    "mapZoom": 12,
    "seeds": [
      "ร้านอาหารไทย กรุงเทพ",
      "ต้มยำกุ้ง กรุงเทพ",
      "ข้าวมันไก่ กรุงเทพ",
      "ก๋วยเตี๋ยวเรือ กรุงเทพ",
      "ส้มตำ กรุงเทพ",
      "ข้าวขาหมู กรุงเทพ",
      "ผัดไทย กรุงเทพ",
      "สตรีทฟู้ด เยาวราช",
      "ร้านอาหารจีน เยาวราช",
      "ติ่มซำ กรุงเทพ",
      "ร้านอาหารญี่ปุ่น กรุงเทพ",
      "ซูชิ กรุงเทพ",
      "ราเมง กรุงเทพ",
      "อาหารเกาหลี กรุงเทพ",
      "หมูกระทะ กรุงเทพ",
      "ชาบู กรุงเทพ",
      "ร้านอาหารอิตาเลียน กรุงเทพ",
      "พิซซ่า กรุงเทพ",
      "สเต๊ก กรุงเทพ",
      "เบอร์เกอร์ กรุงเทพ",
      "อาหารอินเดีย กรุงเทพ",
      "อาหารเวียดนาม กรุงเทพ",
      "ซีฟู้ด กรุงเทพ",
      "บุฟเฟ่ต์ กรุงเทพ",
      "ร้านอาหารริมน้ำ กรุงเทพ",
      "คาเฟ่ อารีย์",
      "คาเฟ่ ทองหล่อ",
      "คาเฟ่ สามย่าน",
      "ร้านกาแฟ specialty กรุงเทพ",
      "ร้านขนมหวาน กรุงเทพ",
      "รูฟท็อปบาร์ กรุงเทพ",
      "บาร์ ทองหล่อ",
      "วัด กรุงเทพ",
      "วัดอรุณ",
      "วัดพระแก้ว",
      "ที่เที่ยว กรุงเทพ",
      "ตลาดนัดจตุจักร",
      "ไอคอนสยาม",
      "ตลาดน้ำ กรุงเทพ",
      "สวนลุมพินี",
      "พิพิธภัณฑ์ กรุงเทพ",
      "ถนนข้าวสาร",
      "เยาวราช",
      "ห้างสรรพสินค้า กรุงเทพ"
    ]
  },
  "tokyo": {
    "name": "Tokyo",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "Shibuya Station",
      "lat": 35.658,
      "lng": 139.7016
    },
    "searchRadiusKm": 18,
    "mapZoom": 12,
    "travelMode": "WALK",
    "seeds": [
      "sushi Tokyo",
      "ramen Tokyo",
      "tempura Tokyo",
      "yakitori Tokyo",
      "tonkatsu Tokyo",
      "udon soba Tokyo",
      "izakaya Shinjuku",
      "unagi Tokyo",
      "wagyu beef Tokyo",
      "sukiyaki shabu Tokyo",
      "ramen Shinjuku",
      "sushi Shibuya",
      "curry Tokyo",
      "seafood Tokyo",
      "yakiniku Tokyo",
      "cafe Shibuya",
      "cafe Omotesando",
      "specialty coffee Tokyo",
      "dessert Tokyo",
      "bakery Tokyo",
      "italian restaurant Tokyo",
      "french restaurant Tokyo",
      "korean food Shin-Okubo",
      "chinese food Tokyo",
      "rooftop bar Tokyo",
      "temple Tokyo",
      "Senso-ji Asakusa",
      "tourist attractions Tokyo",
      "museum Tokyo",
      "market Tokyo",
      "Tsukiji outer market",
      "shopping Ginza"
    ]
  },
  "nikko": {
    "name": "นิกโก้",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "สถานีนิกโก้",
      "lat": 36.7196,
      "lng": 139.6982
    },
    "searchRadiusKm": 35,
    "mapZoom": 11,
    "travelMode": "DRIVE",
    "seeds": [
      "Nikko Toshogu shrine",
      "Kegon Falls Nikko",
      "Lake Chuzenji",
      "Nikko onsen ryokan",
      "yuba tofu Nikko restaurant",
      "Nikko soba",
      "cafe Nikko",
      "Nikko nature waterfall",
      "Nikko roadside station michinoeki",
      "Shinkyo Bridge Nikko",
      "Nikko sightseeing",
      "Nikko souvenir sweets"
    ]
  },
  "aizu": {
    "name": "ไอสึ/ฟุกุชิมะ",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "ปราสาททสึรุกะ",
      "lat": 37.4879,
      "lng": 139.9297
    },
    "searchRadiusKm": 42,
    "mapZoom": 11,
    "travelMode": "DRIVE",
    "seeds": [
      "Aizuwakamatsu sightseeing",
      "Tsuruga Castle Aizu",
      "Ouchijuku",
      "Lake Inawashiro",
      "Aizu onsen",
      "Kitakata ramen",
      "sauce katsudon Aizu",
      "Aizu soba restaurant",
      "cafe Aizu",
      "Aizu roadside station michinoeki",
      "Aizu sake brewery",
      "Aizu nature waterfall"
    ]
  },
  "yamagata": {
    "name": "ยามางาตะ",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "สถานียามางาตะ",
      "lat": 38.2404,
      "lng": 140.3298
    },
    "searchRadiusKm": 42,
    "mapZoom": 11,
    "travelMode": "DRIVE",
    "seeds": [
      "Yamagata sightseeing",
      "Zao Onsen Yamagata",
      "Yamadera temple",
      "Ginzan Onsen",
      "Yonezawa beef restaurant",
      "Yamagata soba",
      "Yamagata ramen",
      "cafe Yamagata",
      "Yamagata roadside station michinoeki",
      "imoni Yamagata",
      "Sagae cherry",
      "onsen ryokan Yamagata"
    ]
  },
  "akita": {
    "name": "อาคิตะ (คาคุโนดาเตะ)",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "สถานีคาคุโนดาเตะ",
      "lat": 39.5987,
      "lng": 140.556
    },
    "searchRadiusKm": 42,
    "mapZoom": 11,
    "travelMode": "DRIVE",
    "seeds": [
      "Kakunodate samurai district",
      "Lake Tazawa Akita",
      "Akita sightseeing",
      "Nyuto onsen",
      "kiritanpo Akita restaurant",
      "inaniwa udon",
      "Akita ramen",
      "cafe Kakunodate",
      "Akita roadside station michinoeki",
      "Akita nature",
      "Tazawako",
      "Akita local food"
    ]
  },
  "aomori": {
    "name": "อาโอโมริ",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "สถานีอาโอโมริ",
      "lat": 40.8286,
      "lng": 140.7406
    },
    "searchRadiusKm": 45,
    "mapZoom": 11,
    "travelMode": "DRIVE",
    "seeds": [
      "Aomori sightseeing",
      "Nebuta Museum Warasse",
      "Aomori seafood market nokkedon",
      "Hirosaki Castle",
      "Aomori apple",
      "miso curry milk ramen Aomori",
      "Aomori onsen",
      "cafe Aomori",
      "Aomori roadside station michinoeki",
      "Takayama Inari shrine",
      "Aomori local food",
      "Hirosaki sightseeing"
    ]
  },
  "sendai": {
    "name": "เซนได/มัตสึชิมะ",
    "country": "JP",
    "lang": "th",
    "currency": "¥",
    "origin": {
      "name": "สถานีเซนได",
      "lat": 38.2601,
      "lng": 140.8819
    },
    "searchRadiusKm": 40,
    "mapZoom": 11,
    "travelMode": "DRIVE",
    "seeds": [
      "Sendai gyutan restaurant",
      "Sendai sightseeing",
      "Matsushima bay",
      "Zuiganji temple",
      "Shiogama fish market",
      "Zao Fox Village",
      "Sendai ramen",
      "zunda sweets Sendai",
      "cafe Sendai",
      "Sendai seafood",
      "Sendai roadside station michinoeki",
      "Sendai souvenir"
    ]
  }
};
